# Generated by Django 4.0.1 on 2022-02-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedatetime',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
